const fs = require('fs');

function modifyConfig(config) {
  // 1. Add Q7 to Section 2
  const section2 = config.sections.find(s => s.id === 'section_2');
  if (section2) {
    const q7Exists = section2.questions.some(q => q.id === 'q7');
    if (!q7Exists) {
      section2.questions.push({
        id: 'q7',
        type: 'radio',
        text: '7. What type of content do you PRIMARILY consume while scrolling through your feed?',
        options: [
          'Entertainment & Comedy (Memes, funny reels, viral trends)',
          'News & Current Affairs (Politics, local/global news updates)',
          'Lifestyle & Personal Connections (Friends\' updates, travel, food, fashion)',
          'Educational & Technology (Tech updates, tutorials, informative content)'
        ]
      });
    }
  }

  // 2. Renumber subsequent sections
  // Section 3 (originally Q7-Q9 -> now Q8-Q10)
  const section3 = config.sections.find(s => s.id === 'section_3');
  if (section3 && section3.questions) {
    if (section3.questions[0].id === 'q7') {
      section3.questions[0] = { ...section3.questions[0], id: 'q8', text: '8. I actively experiment with new Generative AI tools (like ChatGPT, Midjourney, AI filters) as soon as they become available.' };
      section3.questions[1] = { ...section3.questions[1], id: 'q9', text: '9. I feel very comfortable interacting with, liking, or sharing content on social media even if I know it is generated by AI.' };
      section3.questions[2] = { ...section3.questions[2], id: 'q10', text: '10. I am highly confident in my personal ability to easily distinguish between a real photograph and a hyper-realistic AI image. (Measures Overconfidence Bias)' };
    }
  }

  // Section 4 (originally Q10-Q12 -> now Q11-Q13)
  const section4 = config.sections.find(s => s.id === 'section_4');
  if (section4 && section4.questions) {
    if (section4.questions[0].id === 'q10') {
      section4.questions[0] = { ...section4.questions[0], id: 'q11', text: '11. I usually double-check the source or search for more information before sharing a news article or an image that evokes strong emotions.' };
      section4.questions[1] = { ...section4.questions[1], id: 'q12', text: '12. I often notice and analyze visual inconsistencies (e.g., weird lighting, unnatural skin textures, impossible background details) in the images I see online.' };
      section4.questions[2] = { ...section4.questions[2], id: 'q13', text: '13. Before believing a viral visual, I actively check the profile or page that posted it to see if they are a trustworthy source.' };
    }
  }
}

// 1. survey_config.json
const configPath = 'd:/Desktop/RESEARCH/survey/research/survey_config.json';
const configData = JSON.parse(fs.readFileSync(configPath, 'utf8'));
modifyConfig(configData);
fs.writeFileSync(configPath, JSON.stringify(configData, null, 2));
console.log('Updated survey_config.json');

// 2. app.js
const appJsPath = 'd:/Desktop/RESEARCH/survey/research/public/app.js';
let appJs = fs.readFileSync(appJsPath, 'utf8');
const appConfigMatch = appJs.match(/const defaultSurveyConfig = (\{[\s\S]*?\});\s*\n\n\/\/ ---/);
if (appConfigMatch) {
  const appConfig = eval('(' + appConfigMatch[1] + ')');
  modifyConfig(appConfig);
  appJs = appJs.replace(appConfigMatch[1], JSON.stringify(appConfig, null, 2));
  fs.writeFileSync(appJsPath, appJs);
  console.log('Updated app.js');
}

// 3. admin.js
const adminJsPath = 'd:/Desktop/RESEARCH/survey/research/public/admin.js';
let adminJs = fs.readFileSync(adminJsPath, 'utf8');
const adminConfigMatch = adminJs.match(/const defaultSurveyConfig = (\{[\s\S]*?\});\s*\n\nlet surveyConfig = /);
if (adminConfigMatch) {
  const adminConfig = eval('(' + adminConfigMatch[1] + ')');
  modifyConfig(adminConfig);
  adminJs = adminJs.replace(adminConfigMatch[1], JSON.stringify(adminConfig, null, 2));
  fs.writeFileSync(adminJsPath, adminJs);
  console.log('Updated admin.js');
}

// 4. server.js
const serverJsPath = 'd:/Desktop/RESEARCH/survey/research/server.js';
let serverJs = fs.readFileSync(serverJsPath, 'utf8');
const serverConfigMatch = serverJs.match(/const defaultSurveyConfig = (\{[\s\S]*?\});\s*\n\n\/\/ API:/);
if (serverConfigMatch) {
  const serverConfig = eval('(' + serverConfigMatch[1] + ')');
  modifyConfig(serverConfig);
  serverJs = serverJs.replace(serverConfigMatch[1], JSON.stringify(serverConfig, null, 2));
  
  // Update mock generator in serverJs
  serverJs = serverJs.replace(/for \(let q = 7; q <= 9; q\+\+\)/g, 'for (let q = 8; q <= 10; q++)');
  serverJs = serverJs.replace(/for \(let q = 10; q <= 12; q\+\+\)/g, 'for (let q = 11; q <= 13; q++)');
  
  // Add q7 to mock generator
  if (!serverJs.includes('answers.q7 = contentTypes')) {
    serverJs = serverJs.replace(
      /const platforms = \[.*?\];/, 
      `const platforms = ["Instagram", "Facebook", "Both equally"];\n  const contentTypes = ["Entertainment & Comedy (Memes, funny reels, viral trends)", "News & Current Affairs (Politics, local/global news updates)", "Lifestyle & Personal Connections (Friends' updates, travel, food, fashion)", "Educational & Technology (Tech updates, tutorials, informative content)"];`
    );
    serverJs = serverJs.replace(
      /answers\.q6 = times\[Math\.floor\(Math\.random\(\) \* times\.length\)\];/,
      `answers.q6 = times[Math.floor(Math.random() * times.length)];\n    answers.q7 = contentTypes[Math.floor(Math.random() * contentTypes.length)];`
    );
  }

  fs.writeFileSync(serverJsPath, serverJs);
  console.log('Updated server.js');
}
