const fs = require('fs');

function modifyConfig(config) {
  // 1. Add Q7 to Section 2
  const section2 = config.sections.find(s => s.id === 'section_2');
  if (section2) {
    const q7Exists = section2.questions.some(q => q.id === 'q7');
    if (!q7Exists) {
      section2.questions.push({
        id: 'q7',
        type: 'radio',
        text: '7. What type of content do you PRIMARILY consume while scrolling through your feed?',
        options: [
          'Entertainment & Comedy (Memes, funny reels, viral trends)',
          'News & Current Affairs (Politics, local/global news updates)',
          'Lifestyle & Personal Connections (Friends\' updates, travel, food, fashion)',
          'Educational & Technology (Tech updates, tutorials, informative content)'
        ]
      });
    }
  }

  // 2. Renumber subsequent sections
  // Section 3
  const section3 = config.sections.find(s => s.id === 'section_3');
  if (section3 && section3.questions) {
    if (section3.questions[0].id === 'q7') {
      section3.questions[0] = { ...section3.questions[0], id: 'q8', text: '8. I actively experiment with new Generative AI tools (like ChatGPT, Midjourney, AI filters) as soon as they become available.' };
      section3.questions[1] = { ...section3.questions[1], id: 'q9', text: '9. I feel very comfortable interacting with, liking, or sharing content on social media even if I know it is generated by AI.' };
      section3.questions[2] = { ...section3.questions[2], id: 'q10', text: '10. I am highly confident in my personal ability to easily distinguish between a real photograph and a hyper-realistic AI image. (Measures Overconfidence Bias)' };
    }
  }

  // Section 4
  const section4 = config.sections.find(s => s.id === 'section_4');
  if (section4 && section4.questions) {
    if (section4.questions[0].id === 'q10') {
      section4.questions[0] = { ...section4.questions[0], id: 'q11', text: '11. I usually double-check the source or search for more information before sharing a news article or an image that evokes strong emotions.' };
      section4.questions[1] = { ...section4.questions[1], id: 'q12', text: '12. I often notice and analyze visual inconsistencies (e.g., weird lighting, unnatural skin textures, impossible background details) in the images I see online.' };
      section4.questions[2] = { ...section4.questions[2], id: 'q13', text: '13. Before believing a viral visual, I actively check the profile or page that posted it to see if they are a trustworthy source.' };
    }
  }
}

// 2. app.js
const appJsPath = 'd:/Desktop/RESEARCH/survey/research/public/app.js';
let appJs = fs.readFileSync(appJsPath, 'utf8');
const appConfigMatch = appJs.match(/const defaultSurveyConfig = (\{[\s\S]*?\});\s*\n\s*\/\/ Base API/);
if (appConfigMatch) {
  const appConfig = eval('(' + appConfigMatch[1] + ')');
  modifyConfig(appConfig);
  appJs = appJs.replace(appConfigMatch[1], JSON.stringify(appConfig, null, 2));
  fs.writeFileSync(appJsPath, appJs);
  console.log('Updated app.js');
} else {
  console.log('Could not find defaultSurveyConfig in app.js');
}
